config/routes.rb
Snowday::Application.routes.draw do
  devise_for :admins
  devise_for :users, :controllers => { :registrations => "ExtendedUsers" }
  
  resources :districts

  resources :notifications

  root :to => "home#index"

end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :district
  validates_presence_of :message
  validates_length_of :message, :maximum => 140, :minimum => 5
  
  before_save :send_text
  
  private

    def send_text
      # Set the SMSified vars
      sms_user = APP_CONFIG['sms_user'] || 'foo'
      sms_password = APP_CONFIG['sms_password'] || 'secret'
      sender_phone = APP_CONFIG['sms_phone'] || '555-555-1212'
      
      # Array of phone numbers from subscribers
      receivers = [];
      
      # Get the subscribers to this district
      subscribers = self.district.users

      # Only text if there are subscribers
      if subscribers.count > 0 
        subscribers.each do |subscriber|
          receivers.push(subscriber.phone)
        end
        oneapi = Smsified::OneAPI.new(:username => sms_user, :password => sms_password)
        oneapi.send_sms :address => receivers, :message => message, :sender_address => sender_phone
      end
      
    end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_filter :authenticate_admin!
  
  # GET /notifications
  # GET /notifications.xml
  def index
    @notifications = current_admin.district.notifications
    @subscribers = current_admin.district.users || []

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @notifications }
    end
  end

  # GET /notifications/1
  # GET /notifications/1.xml
  def show
    @notification = Notification.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @notification }
    end
  end

  # GET /notifications/new
  # GET /notifications/new.xml
  def new
    @notification = Notification.new
    @notification.district = current_admin.district
    @subscribers = current_admin.district.users || []
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @notification }
    end
  end

  # GET /notifications/1/edit
  def edit
    @notification = Notification.find(params[:id])
  end

  # POST /notifications
  # POST /notifications.xml
  def create
    @notification = Notification.new(params[:notification])
    @notification.district = current_admin.district
    @subscribers = current_admin.district.users || []

    respond_to do |format|
      if @notification.save
        format.html { redirect_to(@notification, :notice => 'Notification was successfully created.') }
        format.xml  { render :xml => @notification, :status => :created, :location => @notification }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @notification.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /notifications/1
  # PUT /notifications/1.xml
  def update
    @notification = Notification.find(params[:id])

    respond_to do |format|
      if @notification.update_attributes(params[:notification])
        format.html { redirect_to(@notification, :notice => 'Notification was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @notification.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /notifications/1
  # DELETE /notifications/1.xml
  def destroy
    @notification = Notification.find(params[:id])
    @notification.destroy

    respond_to do |format|
      format.html { redirect_to(notifications_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_form.html.erb
<%= form_for(@notification) do |f| %>
  <% if @notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notification.errors.count, "error") %> prohibited this notification from being saved:</h2>

      <ul>
      <% @notification.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_field :message %>
  </div>
  <div class="field">
    <%= f.label :sent_at %><br />
    <%= f.datetime_select :sent_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notifications/edit.html.erb
<h1>Editing notification</h1>

<%= render 'form' %>

<%= link_to 'Show', @notification %> |
<%= link_to 'Back', notifications_path %>

app/views/notifications/index.html.erb
<h1><%= current_admin.district.name %></h1>
<%= link_to 'Write a New Notification', new_notification_path %>
<h2>Past Notifications</h2>
<table>
  <tr>
    <th>Message</th>
    <th>Sent</th>
  </tr>

<% @notifications.each do |notification| %>
  <tr>
    <td><%= notification.message %></td>
    <td><%= notification.sent_at %></td>
  </tr>
<% end %>
</table>

<br />

app/views/notifications/new.html.erb
<h1>Send a new message for <%= @notification.district.name %></h1>
<div class="subscribers-list">
  <span class="subscriber-count"><%= @subscribers.count %></span>
  <ul>
  <% @subscribers.each do |subscriber| %>
    <li><%= subscriber.email %> (<%= subscriber.phone %>)</li>
  <% end %>
  </ul>
</div>
<%= form_for(@notification) do |f| %>
  <%= render 'shared/error_messages' %>
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_area :message %><br />
    <span class="chars-left"></span>
  </div>
  <div class="actions">
    <%= f.submit "Send Message" %>
  </div>
<% end %>

<%= link_to 'Back', notifications_path %>

app/views/notifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Message:</b>
  <%= @notification.message %>
</p>

<p>
  <b>Sent at:</b>
  <%= @notification.sent_at %>
</p>


<%= link_to 'Edit', edit_notification_path(@notification) %> |
<%= link_to 'Back', notifications_path %>