config/routes.rb
Snowday::Application.routes.draw do
  devise_for :admins
  devise_for :users, :controllers => { :registrations => "ExtendedUsers" }
  
  resources :districts

  resources :notifications

  root :to => "home#index"

end

app/models/district.rb
class District < ActiveRecord::Base
  has_many :notifications, :dependent => :destroy
  has_many :subscriptions
  has_many :users, :through => :subscriptions
  has_one :admin
  validates_presence_of :name
  
  cattr_reader :per_page
  @@per_page = 20

  def display_name
    "#{name}, (#{state_abbr})"
  end
end

app/controllers/districts_controller.rb
class DistrictsController < ApplicationController
  
  # GET /districts
  # GET /districts.xml
  def index
    if params[:state_abbr]
      @districts = District.where(:state_abbr => params[:state_abbr])
    else
      @districts = District.all.paginate :page => params[:page]
    end
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @districts }
      format.json { render :json => @districts }
    end
  end

  # GET /districts/1
  # GET /districts/1.xml
  def show
    @district = District.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @district }
    end
  end

  # GET /districts/new
  # GET /districts/new.xml
  def new
    @district = District.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @district }
    end
  end

  # GET /districts/1/edit
  def edit
    @district = District.find(params[:id])
  end

  # POST /districts
  # POST /districts.xml
  def create
    @district = District.new(params[:district])

    respond_to do |format|
      if @district.save
        format.html { redirect_to(@district, :notice => 'District was successfully created.') }
        format.xml  { render :xml => @district, :status => :created, :location => @district }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @district.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /districts/1
  # PUT /districts/1.xml
  def update
    @district = District.find(params[:id])

    respond_to do |format|
      if @district.update_attributes(params[:district])
        format.html { redirect_to(@district, :notice => 'District was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @district.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /districts/1
  # DELETE /districts/1.xml
  def destroy
    @district = District.find(params[:id])
    @district.destroy

    respond_to do |format|
      format.html { redirect_to(districts_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/districts_helper.rb
module DistrictsHelper
end

app/views/districts/_form.html.erb
<%= form_for(@district) do |f| %>
  <% if @district.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@district.errors.count, "error") %> prohibited this district from being saved:</h2>

      <ul>
      <% @district.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/districts/edit.html.erb
<h1>Editing district</h1>

<%= render 'form' %>

<%= link_to 'Show', @district %> |
<%= link_to 'Back', districts_path %>

app/views/districts/index.html.erb
<h1>Listing districts</h1>

<table>
  <tr>
    <th>School District</th>
    <th>State</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @districts.each do |district| %>
  <tr>
    <td><%= district.name %></td>
    <td><%= district.state_abbr %>
    <td><%= link_to 'Show', district %></td>
    <td><%= link_to 'Edit', edit_district_path(district) %></td>
    <td><%= link_to 'Destroy', district, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>
<%= will_paginate @districts %>
<br />

<%= link_to 'New District', new_district_path %>

app/views/districts/new.html.erb
<h1>New district</h1>

<%= render 'form' %>

<%= link_to 'Back', districts_path %>

app/views/districts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @district.name %>
</p>


<%= link_to 'Edit', edit_district_path(@district) %> |
<%= link_to 'Back', districts_path %>