config/routes.rb
Snowday::Application.routes.draw do
  devise_for :admins
  devise_for :users, :controllers => { :registrations => "ExtendedUsers" }
  
  resources :districts

  resources :notifications

  root :to => "home#index"

end

app/controllers/extended_users_controller.rb
class ExtendedUsersController < Devise::RegistrationsController
  def get_all_districts
    @districts = District.find(:all, :select => District.column_names - ['geom'], :order => 'state_abbr', :limit => 50)
  end
  
  def create
    get_all_districts
    super
  end
  
  def edit
    get_all_districts
  end
  
  def update
    params[:district_list] ||= {}
#    logger.debug "district list = "
#    logger.debug params['district_list']
    get_all_districts
    super
  end
end

app/views/extended_users/edit.html.erb
<h2>Edit <%= resource_name.to_s.humanize %></h2>

<%= form_for(resource, :as => resource_name, :url => registration_path(resource_name), :html => { :method => :put }) do |f| %>
  <%= devise_error_messages! %>

  <p><%= f.label :email %><br />
  <%= f.email_field :email %></p>

  <p><%= f.label :password %> <i>(leave blank if you don't want to change it)</i><br />
  <%= f.password_field :password %></p>

  <p><%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation %></p>

  <p><%= f.label :current_password %> <i>(we need your current password to confirm your changes)</i><br />
  <%= f.password_field :current_password %></p>
  
  <%= @districts.each do |district| %>
    <%= check_box_tag("user[district_list][#{district.id}]", "1", @user.districts.detect{|d| d == district}) %>
    <%= "#{district.display_name}"%><br />
  <% end %>
  
  <p><%= f.submit "Update" %></p>
<% end %>

<h3>Cancel my account</h3>

<p>Unhappy? <%= link_to "Cancel my account", registration_path(resource_name), :confirm => "Are you sure?", :method => :delete %>.</p>

<%= link_to "Back", :back %>

app/views/extended_users/new.html.erb
<h2>Sign up</h2>

<%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
  <%= devise_error_messages! %>

  <p><%= f.label :email %><br />
  <%= f.email_field :email %></p>

  <p><%= f.label :password %><br />
  <%= f.password_field :password %></p>

  <p><%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation %></p>

  <p><%= f.submit "Sign up" %></p>
<% end %>

<%= render :partial => "devise/shared/links" %>